version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      nix-inputs:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(nix)"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      cargo:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(cargo)"
