[package]
name = "scientisto"
version = "0.1.0"
authors = ["Tibor Csóka"]
license = "MIT"
edition = "2021"
description = "A light-weight Rust implementation of the github/scientist library used for careful refactoring of critical code paths."
documentation = ""
homepage = ""
repository = "https://github.com/Teebor-Choka/scientisto"
keywords = ["scientist", "refactoring", "github", "critical paths"]
categories = ["rust-patterns"]
exclude = [".github/", "codecov.yml"]

[dependencies]

[dev-dependencies]
tracing = "0.1.37"

[badges]
maintenance = { status = "actively-developed" }
