name: Security audit
on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  audit:
    name: Rust code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit
      - name: Run cargo audit
        run: cargo audit
