name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  crate:
    name: Crate to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publish to crates.io
        run: cargo publish
  docs:
    name: Documentation to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Generate documentation
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
        run: cargo doc --all-features
      - name: Deploy documentation to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
