---

on:
  push:
    tags:
      - '*'

name: Publish

jobs:
  publish_crate:
    name: Publish crate to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Publish to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish


  publish_docs:
    name: Publish documentation to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Generate documentation
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
        with:
          command: doc

      - name: Deploy documentation to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
